#!/data/data/com.termux/files/usr/bin/bash

set -e

if [ $# -lt 1 ]; then
    echo "Usage: send <recipient@gmail.com>"
    exit 1
fi

RECIPIENT="$1"

printf "Subject: "
read -r SUBJECT

BODY_FILE="$(mktemp)"
vim "$BODY_FILE"

ATTACHMENTS=()

while true; do
    echo
    printf "Add an attachment? [y/N]: "
    read -r ADD_ATTACHMENT

    case "$ADD_ATTACHMENT" in
        y|Y)
            echo
            echo "Select an attachment from the current directory"
            echo

            FILE=$(
                find "$PWD" -type f 2>/dev/null | \
                    fzf \
                        --height=40% \
                        --border \
                        --prompt="Attachment > "
                        )

            [ -z "$FILE" ] && continue

            DUPLICATE=0

            for f in "${ATTACHMENTS[@]}"; do
                if [ "$f" = "$FILE" ]; then
                    DUPLICATE=1
                    break
                fi
            done

            if [ "$DUPLICATE" -eq 1 ]; then
                echo
                echo "⚠ Already attached:"
                echo "  $FILE"
            else
                ATTACHMENTS+=("$FILE")
                echo
                echo "✓ Attached:"
                echo "  $FILE"
            fi
        ;;
        *)
        break
        ;;
    esac
done

echo
echo "────────────────────────────────────────"
echo "             MAIL PREVIEW"
echo "────────────────────────────────────────"
echo
echo "To      : $RECIPIENT"
echo "Subject : $SUBJECT"
echo
echo "Body"
echo "────────────────────────────────────────"

cat "$BODY_FILE"

echo
echo "────────────────────────────────────────"

echo
if [ "${#ATTACHMENTS[@]}" -gt 0 ]; then
    echo "Attachments:"
        for file in "${ATTACHMENTS[@]}"; do
        echo "  ✓ $file"
    done
else
    echo "Attachment: None"
fi

echo
echo "────────────────────────────────────────"
printf "Send? [y/N]: "
read -r CONFIRM

case "$CONFIRM" in
    y|Y)
    echo
    echo "Sending..."
    echo

    if [ "${#ATTACHMENTS[@]}" -gt 0 ]; then
        mutt \
            -s "$SUBJECT" \
            -a "${ATTACHMENTS[@]}" \
            -- "$RECIPIENT" < "$BODY_FILE"
    else
        mutt \
            -s "$SUBJECT" \
            -- "$RECIPIENT" < "$BODY_FILE"
    fi

    STATUS=$?

    echo

    if [ "$STATUS" -eq 0 ]; then
        echo "✓ Mail sent successfully."
        echo "🕒 $(date '+%d-%m-%Y %H:%M:%S')"
    else
        echo "✗ Failed to send mail."
    fi
	;;
   *)
	echo
	echo "Cancelled."
	;;
esac

rm -f "$BODY_FILE"
